# Generated by Django 5.2.11 on 2026-03-17 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='helppost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='helppostcomment',
            name='help_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.helppost'),
        ),
        migrations.AddField(
            model_name='helppostcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharepost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharepostcomment',
            name='share_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.sharepost'),
        ),
        migrations.AddField(
            model_name='sharepostcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
